Repository tryber/sd-011-project-recipes-app, pull requests merged in 2021-08, with the labels that each got.

#363 [Grupo 25] Tela principal de receitas 25 ao 32
  src/components/Cards.js
  src/css/comidas.css
  src/pages/Drink.js
  src/pages/Foods.js
  src/redux/reducers/comidas.js
  src/redux/reducers/index.js
Labels: Code Review, Grupo 25

#369 [Grupo 25] Searchbar requisitos 13 a 18
  src/App.js
  src/components/DrinkCard.js
  src/components/FoodCard.js
  src/components/Header.js
  src/components/SearchBar.js
  src/pages/Drinks.js
  src/pages/Foods.js
  src/redux/actions/index.js
  src/redux/reducers/drinkReducer.js
  src/redux/reducers/foodReducer.js
  src/redux/reducers/index.js
Labels: Code Review, Grupo 25

#311 [Grupo 26] Página principal (comidas | bebidas)
  src/components/DrinksCards.js
  src/components/Header.js
  src/components/MealsCards.js
  src/components/MenuInferior.jsx
  src/components/Searchbar.js
  src/mock/drinks.js
  src/mock/meals.js
  src/pages/TelaPrincipal.js
  src/pages/TelaPrincipalComidas.js
  src/provider/recipesProvider.js
Labels: Code Review

#290 [Grupo 41] - Telas de Explorar
  cypress/integration/explore_by_area_spec.js
  src/components/RecipeCards.js
  src/css/explore.css
  src/pages/Explore.js
  src/pages/ExploreDrinks.js
  src/pages/ExploreDrinksByIngredients.js
  src/pages/ExploreFoods.js
  src/pages/ExploreFoodsByArea.js
  src/pages/ExploreFoodsByIngredients.js
  src/pages/NotFound.js
  src/pages/index.js
  src/routes/Routes.js
Labels: Code Review

#322 [Group 3] - Refact Search Bar Redirect
  src/components/SearchBar.js
Labels: Code Review

#344 [GROUP 3] - Recipes Main Screen
  public/index.html
  src/App.js
  src/components/Header.js
  src/components/RenderCategoriesDrinks.js
  src/components/RenderCategoriesMeals.js
  src/pages/HomeDrinks.js
  src/pages/HomeRecipe.js
  src/pages/Login.js
  src/redux/actions/index.js
Labels: Code Review

#388 [Main group 14] req 82
  src/components/Header.jsx
  src/images/login.png
  src/pages/Login.jsx
  src/pages/Profile.jsx
  src/styles/profile.css
Labels: Code Review

#399 [Groupo 41] - Tela principal de receitas
  src/App.css
  src/components/CategoryButtons.js
  src/components/Footer.js
  src/components/Header.js
  src/components/RecipeCards.js
  src/components/SearchBar.js
  src/css/Header.css
  src/css/RecipeCards.css
  src/pages/Drinks.js
  src/pages/ExploreDrinksByIngredients.js
  src/pages/ExploreFoodsByIngredients.js
  src/pages/Foods.js
  src/pages/Perfil.js
  src/provider/RecipeAppProvider.js
  src/services/categoriesAPI.js
  src/services/categoryAPI.js
Labels: Code Review

#268 Inicia o Header
  src/App.js
  src/Context/MyContext.js
Labels: Code Review

#154 [Group 25] Revenue details
  package.json
  src/App.css
  src/App.js
  src/components/Cards1.js
  src/components/ContinueButton.js
  src/components/DataUserLogin.js
  src/components/DrinkCard.js
  src/components/FavoriteButton.js
  src/components/FoodCard.js
  src/components/Footer.js
  src/components/SearchBar.js
  src/components/ShareButton.js
  src/components/StartButton.js
  src/hooks/useDetailsFetch.js
  src/hooks/useRecomendedItemsFetch.js
  src/pages/DetailsDrinks.js
  src/pages/DetailsFoods.js
  src/pages/Drink.js
  src/pages/Drinks.js
  src/pages/Foods.js
Labels: Code Review, Grupo 25

#470 [Grupo 41] Tela Principal de Receitas
  src/components/CategoryButtons.js
  src/components/DrinksSearchBar.js
  src/components/FoodsSearchBar.js
  src/components/RecipeCards.js
  src/pages/ExploreFoodsByIngredients.js
Labels: Code Review

#501 [Grupo 41] correção de erro 78
  src/components/CategoryButtons.js
  src/components/Header.js
  src/pages/ExploreFoodsByArea.js
Labels: Code Review

#512 [Group 3] - fix carousel map
  src/components/CarouselRecipes.js
Labels: Code Review

#482 [Grupo 25] - resolvendo problemas
  cypress/integration/recipes_list_spec.js
  cypress/mocks/fetch.js
  src/App.js
  src/components/Cards.js
  src/components/Cards1.js
  src/components/FavoriteButton.js
  src/components/Header.js
  src/components/SearchBar.js
  src/pages/Details.js
  src/pages/DetailsDrinks.js
  src/pages/DetailsFoods.js
  src/pages/Drinks.js
  src/pages/Foods.js
  src/pages/MainPage.js
  src/styles/comidas.css
Labels: Code Review, Grupo 25

#523 [Main-Group-14][Req-67]
  src/pages/Explore.jsx
Labels: Code Review

#587 [Grupo 25] - tela receita em progresso
  src/App.js
  src/components/ContinueButton.js
  src/components/FavoriteButton.js
  src/components/ShareButton.js
  src/pages/Details.js
  src/pages/Drinks.js
  src/pages/FoodsInProgress.js
  src/styles/comidas.css
Labels: Code Review, Grupo 25

#603 [Group 3] - In Progress Pages
  src/App.css
  src/App.js
  src/components/CarouselRecipes.js
  src/components/Header.js
  src/components/IngredientsCheckList.js
  src/helper/objToArryOfObj.js
  src/pages/DrinksInProgress.js
  src/pages/MealsInProgress.js
  src/pages/RecipeInProgress.js
Labels: Code Review

#544 [Grupo-25] - Requisitos 09-10
  src/App.js
  src/components/Header.js
  src/components/Header.jsx
  src/pages/Drinks.js
  src/pages/Explore.js
  src/pages/ExploreDrinks.js
  src/pages/ExploreDrinksIngredientes.js
  src/pages/ExploreFoods.js
  src/pages/ExploreFoodsArea.js
  src/pages/ExploreFoodsIngredientes.js
  src/pages/FavoritedRevenues.js
  src/pages/MakedRevenues.js
  src/pages/Perfil.js
  src/styles/header.css
Labels: Code Review, Grupo 25

#642 [Grupo 25] Corrigindo as telas
  cypress/integration/recipes_list_spec.js
  package-lock.json
  src/components/FavoriteButton.js
  src/components/Header.jsx
  src/pages/Details.js
  src/pages/FoodsInProgress.js
Labels: Code Review, Grupo 25

#598 Main group 28 marcos mantovani
  .stylelintrc.json
  README.md
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/components/Footer.js
  src/components/Header.js
  src/components/RenderRecipes.js
  src/components/SearchBar.js
  src/components/SearchBarBtn.js
  src/index.css
  src/pages/Drinks.js
  src/pages/DrinksIgredients.js
  src/pages/Explorer.js
  src/pages/ExplorerDrinks.js
  src/pages/ExplorerFoods.js
  src/pages/Foods.js
  src/pages/FoodsIngredients.js
  src/pages/Login.js
  src/pages/Profile.js
  src/pages/RecipesByLocation.js
  src/redux/reducer/Mechanics.js
  src/services/ApiFetch.js
Labels: Code Review

#654 [Grupo 39] - [ Estilização dos componentes ]
  package-lock.json
  package.json
  src/App.js
  src/Components/HeaderDrink.jsx
  src/Components/HeaderFood.jsx
  src/Components/RecipesList.jsx
  src/Pages/DrinkDetails.jsx
  src/Pages/FoodDetails.jsx
  src/Pages/Login.jsx
  src/Styles/FooterMenu.css
  src/images/Home.svg
  src/images/TRYBE.gif
  src/images/blackHeartIcon.svg
  src/images/profileIcon.svg
  src/images/redHeartIcon.svg
  src/images/searchIcon.svg
  src/images/teste.svg
  src/images/teste2.svg
  src/images/teste3.svg
  src/index.css
Labels: Code Review

#674 [Grupo 25] - Receitas favoritas
  src/components/ShareButton.js
  src/pages/FavoritedRevenues.js
Labels: Code Review, Grupo 25

#698 [Grupo25] tela de receitas feitas
  src/components/DoneRecipeCard.js
  src/components/MakedRevenuesButton.js
  src/pages/MakedRevenues.js
Labels: Code Review, Grupo 25

#695 [Group 25] Explore foods screen
  src/App.js
  src/pages/ExploreDrinks.js
  src/pages/ExploreFoods.js
Labels: Code Review, Grupo 25

#704 [Grupo 25] - Tela de Explorar Ingredientes
  src/App.js
  src/components/Cards.js
  src/components/Header.js
  src/pages/ExploreIngredients.js
  src/pages/FavoritedRevenues.js
  src/pages/MainPage.js
  src/styles/explorerIngredients.css
  src/styles/favorite.css
  src/styles/header.css
Labels: Code Review, Grupo 25

#686 [ Grupo 9 ] Requisito 10
  cypress/integration/header_spec.js
  src/components/Header.js
  src/pages/Explore.js
  src/pages/ExploreFoodOrDrink.js
  src/pages/ExploreIngredients.js
  src/pages/ExploreLocation.js
  src/pages/FavoriteRecipes.js
  src/pages/Profile.js
  src/pages/RecipeDetail.js
  src/pages/RecipeInProgress.js
  src/pages/Recipes.js
  src/pages/RecipesDone.js
  src/reducers/mealsReducer.js
  src/tests/ExploreFoodOrDrink.test.js
  src/tests/ExploreIngredients.test.js
  src/tests/ExploreLocation.test.js
  src/tests/Header.test.js
  src/tests/Login.test.js
  src/tests/RecipeDetail.test.js
  src/tests/RecipeInProgress.test.js
Labels: enhancement

#791 [GRUPO 14]- pagina de receitas prontas
  src/components/BtnFilters.jsx
  src/helpers/Storage.js
  src/helpers/shareLink.jsx
  src/pages/DoneRecipes.jsx
  src/pages/RecipesInProgress.jsx
  src/styles/DoneRecipes.css
Labels: Code Review

#738 [Group 25] Explore area origin
  src/App.js
  src/pages/ExploreFoodsArea.js
  src/pages/NotFound.js
Labels: Code Review, Grupo 25

#718 [Grupo 25] - corrigindo erros
  src/components/Cards.js
  src/components/DataUserLogin.js
  src/components/DoneRecipeCard.js
  src/components/Footer.js
  src/components/Header.js
  src/components/SearchBar.js
  src/components/StartButton.js
  src/index.css
  src/pages/Details.js
  src/pages/Drinks.js
  src/pages/Explore.js
  src/pages/ExploreDrinks.js
  src/pages/ExploreDrinksIngredientes.js
  src/pages/ExploreFoods.js
  src/pages/ExploreFoodsIngredientes.js
  src/pages/FavoritedRevenues.js
  src/pages/FoodsInProgress.js
  src/pages/Login.js
  src/pages/MainPage.js
  src/pages/Perfil.js
  src/styles/comidas.css
  src/styles/header.css
  src/styles/login.css
Labels: Code Review, Grupo 25

#782 [Group 3] - Change BrowserRouter order
  src/App.css
  src/App.js
  src/components/IngredientsCheckList.js
  src/pages/HomeRecipe.js
  src/style/recipesDone.css
Labels: Code Review

#809 [Group 20] detailspage
  src/App.js
  src/StartRecipe.css
  src/components/DrinkCards.js
  src/components/DrinkDetailsCard.js
  src/components/DrinkFavoriteButton.js
  src/components/DrinkRecomendation.js
  src/components/DrinkShareButton.js
  src/components/DrinkStartRecipe.js
  src/components/FavoriteButton.js
  src/components/FoodCards.js
  src/components/FoodDetailsCard.js
  src/components/FoodRecomendation.js
  src/components/ShareButton.js
  src/components/StartRecipe.js
  src/components/index.js
  src/pages/DrinkDetails.js
  src/pages/Drinks.js
  src/pages/FoodDetails.js
  src/redux/actions/drinkActions.js
  src/redux/actions/foodActions.js
  src/redux/reducers/drinkReducer.js
  src/redux/reducers/foodReducer.js
  src/services/fetchAPIDrink.js
  src/services/fetchAPIFood.js
Labels: Code Review

#685 [Grupo 26] Tela de receitas em progresso
  src/App.js
  src/hooks/useCurrentRecipe.js
  src/pages/BebidaEmProgresso.js
  src/pages/ComidaEmProgresso.js
  src/pages/DetalhesBebida.js
  src/pages/DetalhesComida.js
  src/services/getCurrentDate.js
  src/services/getIngredients.js
  src/services/localStorageChecks.js
  src/styles/EmProgresso.css
Labels: Code Review

#772 [Group 15] [Samuel Melo] [Requirement 34]
  src/pages/DrinkDetails.jsx
  src/pages/FoodDetails.jsx
  src/redux/actions/recipeDetailsActions.js
  src/redux/reducers/index.js
  src/redux/reducers/recipeDetailsReducer.js
  src/services/requestMenu.js
  src/tests/requirementsTests/requirement-34.test.js
Labels: Code Review

#732 [Group 15] [Samuel Melo] [Start Recipe Button and Recipe Instructions]
  src/components/common/RecipeInstructions.jsx
  src/components/common/StartRecipeBtn.jsx
  src/hooks/useRecipeStatus.js
  src/pages/DrinkDetails.jsx
  src/pages/DrinkRecipeProgress.jsx
  src/pages/FoodDetails.jsx
  src/pages/FoodRecipeProgress.jsx
  src/styles/components/recipeInstructions.css
  src/styles/components/startRecipeBtn.css
  src/tests/requirementsTests/requirement-33.test.js
  src/tests/requirementsTests/requirement-38.test.js
  src/tests/requirementsTests/requirement-39.test.js
  src/tests/requirementsTests/requirement-40.test.js
  src/tests/requirementsTests/requirement-41.test.js
Labels: Code Review

#815 [Group 15] [Samuel Melo] [Profile Screen]
  src/components/Header/Header.jsx
  src/pages/Profile.jsx
  src/styles/pages/profile.css
  src/tests/requirementsTests/requirement-82.test.js
  src/tests/requirementsTests/requirement-83.test.js
  src/tests/requirementsTests/requirement-84.test.js
  src/tests/requirementsTests/requirement-85.test.js
  src/tests/requirementsTests/requirement-86.test.js
  src/tests/requirementsTests/requirement-87.test.js
Labels: Code Review

#900 [Group 15] [Samuel Melo] [Recommendation Carousel]
  src/components/common/RecipeCard.jsx
  src/components/common/RecipeInstructions.jsx
  src/components/common/RecommendationCarousel.jsx
  src/pages/DrinkDetails.jsx
  src/pages/Drinks.jsx
  src/pages/FoodDetails.jsx
  src/pages/Foods.jsx
  src/redux/reducers/menuReducer.js
  src/styles/components/recipeCard.css
  src/styles/components/recommendationCarousel.css
  src/tests/helper/testRecipeCard.js
  src/tests/mocks/drinks/mockDrinkRecipeDetails.js
  src/tests/mocks/meals/mockMealRecipeDetails.js
  src/tests/requirementsTests/requirement-25.test.js
  src/tests/requirementsTests/requirement-26.test.js
  src/tests/requirementsTests/requirement-28.test.js
  src/tests/requirementsTests/requirement-29.test.js
  src/tests/requirementsTests/requirement-30.test.js
  src/tests/requirementsTests/requirement-31.test.js
  src/tests/requirementsTests/requirement-33.test.js
  src/tests/requirementsTests/requirement-34.test.js
  src/tests/requirementsTests/requirement-35.test.js
  src/tests/requirementsTests/requirement-36.test.js
  src/tests/requirementsTests/requirement-37.test.js
  src/tests/requirementsTests/requirement-38.test.js
  src/tests/requirementsTests/requirement-39.test.js
  src/tests/requirementsTests/requirement-40.test.js
  src/tests/requirementsTests/requirement-41.test.js
  src/tests/requirementsTests/requirement-42.test.js
  src/tests/requirementsTests/requirement-43.test.js
  src/tests/requirementsTests/requirement-44.test.js
  src/tests/requirementsTests/requirement-45.test.js
  src/tests/requirementsTests/requirement-46.test.js
Labels: Code Review

#874 [Grupo 26] Tela de Explorar Ingredientes
  src/App.js
  src/components/MenuInferior.js
  src/pages/DetalhesBebida.js
  src/pages/DetalhesComida.js
  src/pages/ExplorarIngredientes.js
  src/pages/Profile.js
  src/pages/TelaPrincipal.js
  src/provider/recipesProvider.js
  src/services/requestImage.js
  src/services/requestIngredients.js
Labels: Code Review

#801 [Grupo 39 ] - Tela de Receitas Favoritas
  src/Components/CardsFavoriteRecipes.jsx
  src/Pages/DrinkDetails.jsx
  src/Pages/FavoriteRecipes.jsx
  src/Pages/FoodDetails.jsx
  src/Services/saveFavoriteRecipesOnLocalStorage.js
Labels: Code Review

#917 [Grupo 26] Tela de Explorar por Área
  src/App.js
  src/components/DoneRecipesRender.js
  src/components/ReadyRecipeList.js
  src/components/RecipeList.js
  src/components/RenderCard.js
  src/hooks/useCurrentRecipe.js
  src/pages/ExplorarArea.js
  src/pages/ReadyRecipe.js
  src/services/requestAreas.js
Labels: Code Review

#989 [Grupo 13] Receitas Finalizadas
  src/components/CheckboxDrink.js
  src/components/CheckboxMeal.js
  src/pages/RecipeDetails.js
  src/pages/RecipeDrinkInProgress.js
  src/pages/RecipeMealInProgress.js
  src/pages/Recipes.js
Labels: Code Review

#888 [Grupo 41] Tela Receita em Progresso
  package-lock.json
  package.json
  src/components/DrinksSearchBar.js
  src/components/FoodsSearchBar.js
  src/components/RecipeCards.js
  src/components/RenderDrinkProgress.js
  src/components/RenderFoodIngred.js
  src/components/RenderFoodProgress.js
  src/css/RecipeInProgress.css
  src/index.js
  src/pages/DrinksRecipeInProgress.js
  src/pages/FoodsRecipeInProgress.js
Labels: Code Review

#1038 [Grupo 41] Tela Receitas Favoritas Refatorada
  package-lock.json
  package.json
  src/components/DrinksSearchBar.js
  src/components/FoodsSearchBar.js
  src/components/Header.js
  src/components/RecipeDetailsButton.js
  src/components/RenderDrinkDetails.js
  src/components/RenderDrinkProgress.js
  src/components/RenderFoodDetails.js
  src/components/RenderFoodIngred.js
  src/components/RenderFoodInstruction.js
  src/components/RenderFoodProgress.js
  src/components/StartRecipeButton.js
  src/components/checkLocalStorage.js
  src/css/RecipeDetailsButton.css
  src/css/RecipeInProgress.css
  src/index.js
  src/pages/DrinksDetails.js
  src/pages/DrinksRecipeInProgress.js
  src/pages/FavoriteRecipes.js
  src/pages/FoodsDetails.js
  src/pages/FoodsRecipeInProgress.js
  src/pages/RecipesDone.js
  src/provider/RecipeAppProvider.js
Labels: Code Review

#897 [Group 3] - Tests
  src/App.test.js
  src/components/FavBtnFavoritePage.js
  src/components/Redirect.js
  src/components/RenderAll.js
  src/tests/DrinkDetails.test.js
  src/tests/DrinksInProgress.test.js
  src/tests/Explore.test.js
  src/tests/ExploreByIngredients.test.js
  src/tests/ExploreByIngredientsDrinks.test.js
  src/tests/ExploreByLocal.test.js
  src/tests/ExploreDrinks.test.js
  src/tests/ExploreRecipes.test.js
  src/tests/Footer.test.js
  src/tests/HomeDrinks.test.js
  src/tests/HomeMeals.test.js
  src/tests/Login.test.js
  src/tests/MealsDetails.test.js
  src/tests/MealsInProgress.test.js
  src/tests/NotFound.test.js
  src/tests/Profile.test.js
  src/tests/RecipeFavorite.test.js
  src/tests/RecipesDone.test.js
  src/tests/SearchBar.test.js
  src/tests/ShareBtn.test.js
  src/tests/mockPizza.js
  src/tests/renderWithRouterAndRedux.js
Labels: Code Review

#1068 [Grupo 39] - Explore Origem Area
  src/Components/FilterAreaExplore.jsx
  src/Pages/ExploreDrinkOrigin.jsx
  src/Pages/ExploreFoodOrigin.jsx
Labels: Code Review

#1111 [Group 3] - Adjust
  src/pages/DrinkDetails.js
  src/pages/HomeDrinks.js
  src/tests/HomeDrinks.test.js
  src/tests/HomeMeals.test.js
  src/tests/MealsDetails.test.js
  src/tests/Profile.test.js
  src/tests/RecipeFavorite.test.js
Labels: Code Review

#996 [Group 15] [Robson Cardozo] Completed Recipes
  src/pages/CompletedRecipes.jsx
Labels: Code Review
